[package]
name = "marketplace"
version = "0.1.0"
authors = ["Eneftigo <pietrzykowskihubert@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "=4.0.0-pre.4"
chrono = "0.4.19"
url = "2.2.2"
